# Generated by Django 4.0.6 on 2022-08-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_passenger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fligth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightApp.flight'),
        ),
    ]
